#      SavageSkyBlock      #
# Information: https://wiki.prosavage.net/display/savageskyblock/SavageSkyblock #

settings:

  world-name: 'skyBlock'

  faded-item:
    glowing: true
    item-id: 'stained_glass_pane'
    item-data: 15

  config-version: 1.4 # DO NOT CHANGE THIS!!!

  debug: false # if you want debug messages in console enable this, if not set to "false"

  data-save-interval: 5 # in minutes

  quest-requirements-completed-messageInterval: 30 # every 30 seconds we want to notify the player that they have completed this quest's requirements and to complete the quest

  island-bank-name: '&aIsland Bank'

  fafst-break-permission: 'skyblock.fastbreak' # allows players to break blocks fast, similar to Creative Mode

  send-island-enter-message: true # send the "island-enter" message from messages.yml?
  send-island-leave-message: true # send the "island-leave" message from messages.yml?

  disable-fallDamage: true # no fall damage? yes.

  island-fly-permission: 'skyblock.fly' # allows flying on THEIR own Island

  default-hopper-limit: 5 # override with permission: skyblock.block.hopper.NUMBER
  default-spawner-limit: 5 # override with permission: skyblock.block.spawner.NUMBER
  default-member-limit: 5 # override with permission: skyblock.members.NUMBER, permission overrides Upgrade
  default-protection-radius: 50 # 50^4, block radius around each corner of island, override with permission: skyblock.protection.NUMBER
  default-reset-limit: 3 # override with permission: skyblock.resets.NUMBER

  island-level-calculation-time: 60 # in seconds
  island-level-placeholder: '%is-level%' # can use this in chat formatting
  broadcast-isTop-calculations: true

  invalid-island-top-name-placeholders: '&cInvalid Island'
  invalid-island-top-lore-placeholders: '&c&lN/A'

  use-chat-format: true
  chat-format: '&a{is-level} &7[&9{is-top}&7] &r{old-format}'

  island-distance: 100 # 100 blocks away from the nearest island....
  min-x: 0 # the starting point on the x axis to start plotting islands
  min-z: 0 # the starting point on the z axis to start plotting islands
  max-x: 1000 # the ending point on the x axis to stop plotting islands
  max-z: 1000 # the ending point on the z axis to stop plotting islands

  default-biome: 'PLAINS'
  inviteExpireTime: 10 # seconds

  island-spawn: 'not-set' # set using /isa setspawn